# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: one-watcher

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Generating Charts...
      run: |
        bash ./one 5

    - name: commit
      id: commit
      run: |
        git config --global user.email brx86@qq.com
        git config --global user.name action_bot
        git add .
        git commit -m "update up web"
      continue-on-error: true

    - name: Check on failures
      if: steps.commit.outputs.status == 'failure'
      run: exit 1

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
